---
title: "Movie App"
format: 
  html:
    page-layout: custom
server: shiny
---

```{r}
#| panel: input
#| layout-ncol: 2

sliderInput("year_filter", 
      "Select Highest Year", 
      min = 1915,
      max=2014, 
      value = 2014)


selectInput(inputId = "color_select", 
              label = "Select Categorical Variable", 
              choices = c("country", "type_of_subject", 
                          "subject_race", "subject_sex"))
```


```{r}
plotOutput("movie_plot")
```

```{r}
plotOutput("movie_hist")
```


```{r}
#| context: setup
#| message: false
#| echo: false
library(shiny)
library(tidyverse)
library(fivethirtyeight)

##load the biopics data
data(biopics)
biopics <- biopics %>% filter(!is.na(box_office))
categoricalVars <- c("country", "type_of_subject", "subject_race", "subject_sex")

```

```{r}
#| context: server
  biopics_filtered <- reactive({
    req(input$year_filter)
    biopics %>%
        filter(year_release < input$year_filter)
    
     })
   
   output$movie_plot <- renderPlot({
      
       ggplot(biopics_filtered()) +
         aes(y=box_office, 
         x=year_release,
         color=.data[[input$color_select]]) + 
       geom_point()
     
   })
   
   output$movie_hist <- renderPlot({
      
       ggplot(biopics_filtered()) +
         aes(x=box_office, 
         fill=.data[[input$color_select]]) + 
       geom_histogram()
     
   })
```
